/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FACTURAS;

/**
 *
 * @author Ariel
 */
public class MAIN extends javax.swing.JFrame {

    /**
     * Creates new form MAIN
     */
    public MAIN() {
       //this.setExtendedState(500);
          initComponents();
      this.setSize(600, 500);
    
      this.setLocationRelativeTo(this);
       

        
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principal = new javax.swing.JDialog();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Configuracion = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Agregar_Usuario = new javax.swing.JDialog();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        Eliminar_usu = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton10 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        Modificar_usu = new javax.swing.JDialog();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        Menu_Facturas = new javax.swing.JDialog();
        jLabel24 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        factu_cajas = new javax.swing.JDialog();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        label_codigo = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        f_proseso = new javax.swing.JDialog();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jTextField31 = new javax.swing.JTextField();
        jTextField32 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        f_proforma = new javax.swing.JDialog();
        jTextField33 = new javax.swing.JTextField();
        jTextField34 = new javax.swing.JTextField();
        jTextField35 = new javax.swing.JTextField();
        jTextField36 = new javax.swing.JTextField();
        jTextField37 = new javax.swing.JTextField();
        jTextField38 = new javax.swing.JTextField();
        jTextField39 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel31 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jt_nombre_usuario = new javax.swing.JTextField();
        jt_contra_usuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        principal.setMinimumSize(new java.awt.Dimension(788, 500));
        principal.getContentPane().setLayout(null);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/INTERFACES/tool_icon.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        principal.getContentPane().add(jButton2);
        jButton2.setBounds(180, 140, 100, 100);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/INTERFACES/icono_factura.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        principal.getContentPane().add(jButton3);
        jButton3.setBounds(420, 140, 100, 100);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel2.setText("Configuracion");
        principal.getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 98, 148, 29);

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel3.setText("Documentos");
        principal.getContentPane().add(jLabel3);
        jLabel3.setBounds(400, 100, 142, 29);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/INTERFACES/principal.png"))); // NOI18N
        principal.getContentPane().add(jLabel4);
        jLabel4.setBounds(-30, 0, 880, 580);

        jMenu1.setText("Menu");
        jMenuBar1.add(jMenu1);

        principal.setJMenuBar(jMenuBar1);

        Configuracion.setLocationByPlatform(true);
        Configuracion.setMinimumSize(new java.awt.Dimension(789, 580));
        Configuracion.setUndecorated(true);
        Configuracion.getContentPane().setLayout(null);

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel5.setText("Agregar Usuario");
        Configuracion.getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 70, 146, 23);

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel6.setText("Eliminar Usuario");
        Configuracion.getContentPane().add(jLabel6);
        jLabel6.setBounds(470, 70, 148, 23);

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel7.setText("Modificar Usuario");
        Configuracion.getContentPane().add(jLabel7);
        jLabel7.setBounds(300, 240, 155, 23);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/INTERFACES/agregar icon_2.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        Configuracion.getContentPane().add(jButton4);
        jButton4.setBounds(180, 100, 120, 100);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/INTERFACES/icon delete_2.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        Configuracion.getContentPane().add(jButton5);
        jButton5.setBounds(490, 100, 130, 100);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/INTERFACES/mod_icon_2.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        Configuracion.getContentPane().add(jButton6);
        jButton6.setBounds(320, 280, 120, 100);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/INTERFACES/salir_icon_2.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        Configuracion.getContentPane().add(jButton7);
        jButton7.setBounds(30, 440, 160, 110);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/INTERFACES/configuracion_interfaz.png"))); // NOI18N
        Configuracion.getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 800, 570);

        Agregar_Usuario.setMinimumSize(new java.awt.Dimension(789, 500));
        Agregar_Usuario.getContentPane().setLayout(null);

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel9.setText("Nombre Completo: ");
        Agregar_Usuario.getContentPane().add(jLabel9);
        jLabel9.setBounds(70, 100, 160, 32);
        Agregar_Usuario.getContentPane().add(jTextField1);
        jTextField1.setBounds(270, 100, 240, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Identidad: ");
        Agregar_Usuario.getContentPane().add(jLabel10);
        jLabel10.setBounds(90, 180, 100, 22);
        Agregar_Usuario.getContentPane().add(jTextField2);
        jTextField2.setBounds(270, 170, 240, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Nombre Usuario: ");
        Agregar_Usuario.getContentPane().add(jLabel11);
        jLabel11.setBounds(60, 240, 158, 22);
        Agregar_Usuario.getContentPane().add(jTextField3);
        jTextField3.setBounds(270, 230, 240, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Contraseña: ");
        Agregar_Usuario.getContentPane().add(jLabel12);
        jLabel12.setBounds(80, 290, 116, 22);
        Agregar_Usuario.getContentPane().add(jTextField4);
        jTextField4.setBounds(270, 290, 242, 30);

        jButton8.setText("AGREGAR");
        Agregar_Usuario.getContentPane().add(jButton8);
        jButton8.setBounds(350, 350, 110, 80);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Agregacion de Usuario ");
        Agregar_Usuario.getContentPane().add(jLabel14);
        jLabel14.setBounds(290, 10, 240, 22);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/INTERFACES/salir_icon_2.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        Agregar_Usuario.getContentPane().add(jButton9);
        jButton9.setBounds(650, 20, 110, 100);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/INTERFACES/configuracion_interfaz.png"))); // NOI18N
        Agregar_Usuario.getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 0, 800, 490);

        Eliminar_usu.setMinimumSize(new java.awt.Dimension(789, 500));
        Eliminar_usu.getContentPane().setLayout(null);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Eliminar Usuario");
        Eliminar_usu.getContentPane().add(jLabel15);
        jLabel15.setBounds(250, 10, 170, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Usuarios: ");
        Eliminar_usu.getContentPane().add(jLabel16);
        jLabel16.setBounds(160, 90, 100, 20);

        Eliminar_usu.getContentPane().add(jComboBox1);
        jComboBox1.setBounds(260, 80, 180, 30);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/INTERFACES/icon delete_2.png"))); // NOI18N
        Eliminar_usu.getContentPane().add(jButton10);
        jButton10.setBounds(290, 230, 130, 120);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/INTERFACES/configuracion_interfaz.png"))); // NOI18N
        Eliminar_usu.getContentPane().add(jLabel17);
        jLabel17.setBounds(0, 0, 770, 450);

        Modificar_usu.setMinimumSize(new java.awt.Dimension(789, 500));
        Modificar_usu.getContentPane().setLayout(null);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Modificar Usuario");
        Modificar_usu.getContentPane().add(jLabel18);
        jLabel18.setBounds(310, 10, 190, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Usuario: ");
        Modificar_usu.getContentPane().add(jLabel19);
        jLabel19.setBounds(140, 80, 80, 22);

        Modificar_usu.getContentPane().add(jComboBox2);
        jComboBox2.setBounds(220, 80, 200, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Nombre: ");
        Modificar_usu.getContentPane().add(jLabel20);
        jLabel20.setBounds(130, 180, 70, 20);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Usuario: ");
        Modificar_usu.getContentPane().add(jLabel21);
        jLabel21.setBounds(130, 220, 70, 20);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Contraseña: ");
        Modificar_usu.getContentPane().add(jLabel22);
        jLabel22.setBounds(130, 270, 100, 20);
        Modificar_usu.getContentPane().add(jTextField5);
        jTextField5.setBounds(220, 270, 190, 30);
        Modificar_usu.getContentPane().add(jTextField6);
        jTextField6.setBounds(220, 180, 190, 30);
        Modificar_usu.getContentPane().add(jTextField7);
        jTextField7.setBounds(220, 220, 190, 30);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/INTERFACES/mod_icon_2.png"))); // NOI18N
        Modificar_usu.getContentPane().add(jButton11);
        jButton11.setBounds(480, 280, 90, 70);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/INTERFACES/configuracion_interfaz.png"))); // NOI18N
        Modificar_usu.getContentPane().add(jLabel23);
        jLabel23.setBounds(0, 0, 850, 450);

        Menu_Facturas.setMinimumSize(new java.awt.Dimension(789, 500));
        Menu_Facturas.getContentPane().setLayout(null);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("Factura PROSESO");
        Menu_Facturas.getContentPane().add(jLabel24);
        jLabel24.setBounds(270, 80, 170, 30);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/INTERFACES/icon_caja_2.png"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        Menu_Facturas.getContentPane().add(jButton12);
        jButton12.setBounds(80, 130, 110, 100);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setText("Recibo de Cajas");
        Menu_Facturas.getContentPane().add(jLabel26);
        jLabel26.setBounds(50, 80, 170, 30);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setText("Factura PROFORMA");
        Menu_Facturas.getContentPane().add(jLabel30);
        jLabel30.setBounds(500, 80, 190, 22);

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/INTERFACES/icon_proseso.png"))); // NOI18N
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        Menu_Facturas.getContentPane().add(jButton16);
        jButton16.setBounds(300, 120, 110, 100);

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/INTERFACES/tool_icon.png"))); // NOI18N
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        Menu_Facturas.getContentPane().add(jButton17);
        jButton17.setBounds(510, 120, 150, 100);

        factu_cajas.setMinimumSize(new java.awt.Dimension(970, 650));
        factu_cajas.getContentPane().setLayout(null);
        factu_cajas.getContentPane().add(jTextField8);
        jTextField8.setBounds(740, 220, 150, 30);
        factu_cajas.getContentPane().add(jTextField9);
        jTextField9.setBounds(180, 290, 370, 30);
        factu_cajas.getContentPane().add(jTextField10);
        jTextField10.setBounds(680, 290, 210, 30);
        factu_cajas.getContentPane().add(jTextField11);
        jTextField11.setBounds(180, 330, 380, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        factu_cajas.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(180, 440, 710, 40);
        factu_cajas.getContentPane().add(jTextField12);
        jTextField12.setBounds(180, 380, 720, 30);
        factu_cajas.getContentPane().add(jTextField13);
        jTextField13.setBounds(180, 520, 110, 20);
        factu_cajas.getContentPane().add(jTextField14);
        jTextField14.setBounds(180, 540, 110, 20);

        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });
        factu_cajas.getContentPane().add(jTextField15);
        jTextField15.setBounds(180, 560, 110, 20);

        label_codigo.setText("jLabel26");
        factu_cajas.getContentPane().add(label_codigo);
        label_codigo.setBounds(730, 110, 110, 50);

        jButton14.setText("REGISTRAR");
        factu_cajas.getContentPane().add(jButton14);
        jButton14.setBounds(820, 523, 110, 70);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/INTERFACES/Factura#1.png"))); // NOI18N
        jLabel27.setText("jLabel27");
        factu_cajas.getContentPane().add(jLabel27);
        jLabel27.setBounds(0, 0, 1040, 680);

        f_proseso.setMinimumSize(new java.awt.Dimension(1000, 1000));
        f_proseso.getContentPane().setLayout(null);
        f_proseso.getContentPane().add(jTextField16);
        jTextField16.setBounds(70, 160, 670, 50);
        f_proseso.getContentPane().add(jTextField17);
        jTextField17.setBounds(90, 230, 670, 40);
        f_proseso.getContentPane().add(jTextField18);
        jTextField18.setBounds(830, 230, 110, 20);
        f_proseso.getContentPane().add(jTextField19);
        jTextField19.setBounds(830, 190, 120, 30);
        f_proseso.getContentPane().add(jTextField20);
        jTextField20.setBounds(60, 280, 120, 50);

        buttonGroup1.add(jRadioButton1);
        f_proseso.getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(260, 300, 30, 21);

        buttonGroup1.add(jRadioButton2);
        f_proseso.getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(360, 300, 30, 21);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Descripcion", "Cantidad", "P./Unitario", "%IVS", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        f_proseso.getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(0, 330, 960, 190);
        f_proseso.getContentPane().add(jTextField22);
        jTextField22.setBounds(370, 720, 260, 20);

        jTextField23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField23ActionPerformed(evt);
            }
        });
        f_proseso.getContentPane().add(jTextField23);
        jTextField23.setBounds(660, 590, 100, 20);

        jTextField24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField24ActionPerformed(evt);
            }
        });
        f_proseso.getContentPane().add(jTextField24);
        jTextField24.setBounds(840, 600, 100, 20);

        jTextField25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField25ActionPerformed(evt);
            }
        });
        f_proseso.getContentPane().add(jTextField25);
        jTextField25.setBounds(840, 550, 100, 20);

        jTextField26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField26ActionPerformed(evt);
            }
        });
        f_proseso.getContentPane().add(jTextField26);
        jTextField26.setBounds(520, 600, 110, 20);

        jTextField27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField27ActionPerformed(evt);
            }
        });
        f_proseso.getContentPane().add(jTextField27);
        jTextField27.setBounds(650, 550, 110, 20);
        f_proseso.getContentPane().add(jTextField28);
        jTextField28.setBounds(520, 550, 100, 20);
        f_proseso.getContentPane().add(jTextField29);
        jTextField29.setBounds(370, 680, 260, 20);
        f_proseso.getContentPane().add(jTextField30);
        jTextField30.setBounds(370, 700, 260, 20);
        f_proseso.getContentPane().add(jTextField31);
        jTextField31.setBounds(400, 600, 80, 20);
        f_proseso.getContentPane().add(jTextField32);
        jTextField32.setBounds(400, 550, 80, 20);

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/INTERFACES/factura_0.1.2.png"))); // NOI18N
        f_proseso.getContentPane().add(jLabel29);
        jLabel29.setBounds(0, 520, 960, 340);

        jButton15.setText("REGISTRAR");
        f_proseso.getContentPane().add(jButton15);
        jButton15.setBounds(750, 870, 160, 40);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setText("jLabel28");
        f_proseso.getContentPane().add(jLabel28);
        jLabel28.setBounds(680, 284, 170, 30);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/INTERFACES/factura_0.2.png"))); // NOI18N
        jLabel25.setText("jLabel25");
        f_proseso.getContentPane().add(jLabel25);
        jLabel25.setBounds(0, 0, 970, 330);

        f_proforma.setPreferredSize(new java.awt.Dimension(1000, 1000));
        f_proforma.getContentPane().setLayout(null);
        f_proforma.getContentPane().add(jTextField33);
        jTextField33.setBounds(790, 290, 120, 20);
        f_proforma.getContentPane().add(jTextField34);
        jTextField34.setBounds(100, 270, 380, 20);
        f_proforma.getContentPane().add(jTextField35);
        jTextField35.setBounds(100, 290, 680, 20);
        f_proforma.getContentPane().add(jTextField36);
        jTextField36.setBounds(790, 270, 130, 20);
        f_proforma.getContentPane().add(jTextField37);
        jTextField37.setBounds(100, 250, 380, 20);
        f_proforma.getContentPane().add(jTextField38);
        jTextField38.setBounds(630, 250, 150, 20);
        f_proforma.getContentPane().add(jTextField39);
        jTextField39.setBounds(630, 270, 150, 20);

        jLabel32.setText("jLabel32");
        f_proforma.getContentPane().add(jLabel32);
        jLabel32.setBounds(610, 80, 40, 14);

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/INTERFACES/factura_3.png"))); // NOI18N
        f_proforma.getContentPane().add(jLabel33);
        jLabel33.setBounds(0, -40, 930, 400);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Cantidad", "Descripcion", "Precio Unit", "Desc & Reb.Otogado", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable2);

        f_proforma.getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(0, 310, 920, 120);

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/INTERFACES/factura_0.3.png"))); // NOI18N
        f_proforma.getContentPane().add(jLabel31);
        jLabel31.setBounds(160, 430, 570, 230);

        jButton13.setText("REGISTRAR");
        f_proforma.getContentPane().add(jButton13);
        jButton13.setBounds(790, 590, 110, 60);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/INTERFACES/INGRESAR_2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 360, 87, 101);

        jt_nombre_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_nombre_usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jt_nombre_usuario);
        jt_nombre_usuario.setBounds(40, 140, 220, 30);
        getContentPane().add(jt_contra_usuario);
        jt_contra_usuario.setBounds(40, 290, 220, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/INTERFACES/LOGIN_PROCESO.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 650, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jt_nombre_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_nombre_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_nombre_usuarioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        configura();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        principal();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Eliminar();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
       Configuracion.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        agregar_usu();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        Agregar_Usuario.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        mod_usu();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        reci_cajas();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        menu_fact();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jTextField24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField24ActionPerformed

    private void jTextField25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField25ActionPerformed

    private void jTextField26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField26ActionPerformed

    private void jTextField27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField27ActionPerformed

    private void jTextField23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField23ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        fac_proseso();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        fa_proforma();
    }//GEN-LAST:event_jButton17ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MAIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MAIN().setVisible(true);
            }
        });
    }
    
     public void principal() {
            principal.setSize(500, 500);
        principal.pack();
        principal.setModal(true);
        principal.setLocationRelativeTo(this);
        principal.setVisible(true);
       
       
    }
          public void configura() {
           Configuracion.setSize(500, 500);
        Configuracion.pack();
        Configuracion.setModal(true);
        Configuracion.setLocationRelativeTo(this);
        Configuracion.setVisible(true);
       
      
    }
    
            public void agregar_usu() {
           Agregar_Usuario.setSize(500, 500);
        Agregar_Usuario.pack();
        Agregar_Usuario.setModal(true);
        Agregar_Usuario.setLocationRelativeTo(this);
        Agregar_Usuario.setVisible(true);
       
      
    }
        public void Eliminar() {
           Eliminar_usu.setSize(500, 500);
        Eliminar_usu.pack();
        Eliminar_usu.setModal(true);
        Eliminar_usu.setLocationRelativeTo(this);
        Eliminar_usu.setVisible(true);
       
      
    }
          
           public void mod_usu() {
           Modificar_usu.setSize(500, 500);
        Modificar_usu.pack();
        Modificar_usu.setModal(true);
        Modificar_usu.setLocationRelativeTo(this);
        Modificar_usu.setVisible(true);
       
      
    }
           
            public void menu_fact() {
           Menu_Facturas.setSize(500, 500);
        Menu_Facturas.pack();
        Menu_Facturas.setModal(true);
        Menu_Facturas.setLocationRelativeTo(this);
        Menu_Facturas.setVisible(true);
       
      
    }     
         public void reci_cajas() {
           factu_cajas.setSize(500, 500);
        factu_cajas.pack();
        factu_cajas.setModal(true);
        factu_cajas.setLocationRelativeTo(this);
        factu_cajas.setVisible(true);
       
      
    }     
         
        public void fac_proseso() {
        f_proseso.setSize(500, 500);
        f_proseso.pack();
        f_proseso.setModal(true);
        f_proseso.setLocationRelativeTo(this);
        f_proseso.setVisible(true); 
    }     
        
        
          public void fa_proforma() {
        f_proforma.setSize(500, 500);
        f_proforma.pack();
        f_proforma.setModal(true);
        f_proforma.setLocationRelativeTo(this);
        f_proforma.setVisible(true); 
    }     


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Agregar_Usuario;
    private javax.swing.JDialog Configuracion;
    private javax.swing.JDialog Eliminar_usu;
    private javax.swing.JDialog Menu_Facturas;
    private javax.swing.JDialog Modificar_usu;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JDialog f_proforma;
    private javax.swing.JDialog f_proseso;
    private javax.swing.JDialog factu_cajas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jt_contra_usuario;
    private javax.swing.JTextField jt_nombre_usuario;
    private javax.swing.JLabel label_codigo;
    private javax.swing.JDialog principal;
    // End of variables declaration//GEN-END:variables
}
